name: Build ZLUDA DLL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.26.4'

    - name: Configure project
      run: cmake -S ZLUDA -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release

    - name: Upload zluda64.dll
      uses: actions/upload-artifact@v4
      with:
        name: zluda64-dll
        path: build/ZLUDA/zluda64.dll
