name: Build ZLUDA DLL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup CMake
      uses: lukka/get-cmake@v3

    - name: Configure project
      run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release

    - name: Upload zluda64.dll
      uses: actions/upload-artifact@v3
      with:
        name: zluda64-dll
        path: build\zluda64.dll
